name: arduino/arduino-lint-action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Temporarily hide sketch.yaml
      run: mv sketch/sketch.yaml sketch/sketch.yaml.bak
    - name: Lint Sketch
      uses: arduino/arduino-lint-action@v2
      with:
        path: sketch/
        library-manager: false
        compliance: strict
        verbose: true
        recursive: false
    - name: Restore sketch.yaml
      run: mv sketch/sketch.yaml.bak sketch/sketch.yaml
